version: "3.3" # optional since v1.27.0
services:
  main:
    image: registry:2
    ports:
      - "5000:5000"
  proxy:
    image: registry:2
    ports:
      - "5005:5000"
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
